language: node_js

node_js:
  - '10'

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  yarn: true

after_success:
  - yarn test --coverage --coverageReporters=text-lcov | yarn run coveralls

before_deploy:
  - yarn build

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
